# This ApplicationSet discovers and deploys tenants based on individual YAML files in Git.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dubai-appset
  namespace: argocd
spec:
  # Use the Git generator to find files matching a wildcard path.
  generators:
    - git:
        repoURL: https://github.com/ujimatech/dubai.git # The repo where this file lives.
        revision: multitenant-argocd
        files:
          # This is the key: discover every .yaml file inside the 'tenants' directory.
          - path: "tenants/*.yaml"

  # The template uses the content of each discovered file to generate an application.
  template:
    metadata:
      # '{{.projectName}}' and '{{.entityId}}' are fields from a tenant's YAML file.
      name: '{{projectName}}-{{entityId}}'
    spec:
      project: '{{projectName}}-{{entityId}}'
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{targetRevision}}"
        path: "terraform/dubai-bundle" # Path to the App of Apps chart
        helm:
          releaseName: "{{projectName}}-{{entityId}}"
          parameters:
            - name: "global.entityId"
              value: "{{entityId}}"
            - name: "global.projectName"
              value: "{{projectName}}"
            - name: "spec.source.repoURL"
              value: "{{repoURL}}"
            - name: "spec.source.targetRevision"
              value: "{{targetRevision}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{projectName}}-{{entityId}}"
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ "CreateNamespace=true" ]