global:
  projectName: ""
  entityId: ""

openwebui:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: v0.6.15
    pullPolicy: IfNotPresent
  persistence:
    storageClassName: ""
  service:
    type: NodePort
    port: 8080
    nodePort: 30003
  env:
    STORAGE_PROVIDER: s3
    S3_ENDPOINT_URL: https://s3.us-west-2.amazonaws.com
    S3_REGION_NAME: us-west-2
    S3_BUCKET_NAME: "dubai-openwebui-storage"
    ENV: dev
    OPENAI_API_BASE_URL: ""
    RAG_OPENAI_API_BASE_URL: ""
    RAG_EMBEDDING_ENGINE: openai
    RAG_EMBEDDING_MODEL: cohere.embed-english-v3
  secrets:
    OPENAI_API_KEY: ""
    RAG_OPENAI_API_KEY: ""
    S3_ACCESS_KEY_ID: ""
    S3_SECRET_ACCESS_KEY: ""
    DATABASE_URL: ""
    PGVECTOR_DB_URL: ""

litellm:
  image:
    repository: ghcr.io/berriai/litellm
    tag: main-latest
    pullPolicy: IfNotPresent
  persistence:
    storageClassName: ""
  service:
    type: ClusterIP
    port: 80
  env:
    DEBUG: true
    DEFAULT_EMBEDDING_MODEL: cohere.embed-multilingual-v3
    ENABLE_CROSS_REGION_INFERENCE: true
    LITELLM_CONFIG: "/app/config.yaml"
  secrets:
    master_key: ""
  openrouter:
    api_base_url: "https://openrouter.ai/api/v1"
    openrouter_api_key: ""
  aws:
    irsa:
      roleArn: "arn:aws:iam::166531731337:role/k3s-irsa-awscli"



