apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-dock-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcp-dock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClassName | default "longhorn" }}
