apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: {{ .Values.global.projectName }}-{{ .Values.global.entityId}}-snapshot-job
  namespace: longhorn-system
spec:
  cron: "*/10 * * * *"
  task: "snapshot"
  groups:
  - {{ .Values.global.projectName }}-{{ .Values.global.entityId}}
  retain: 1
  concurrency: 2
