---
- hosts: tailscale_router
  become: yes
  tasks:
    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present
        update_cache: yes

    - name: Backup original dnsmasq config
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.backup
        remote_src: yes
        force: no

    - name: Configure dnsmasq
      template:
        src: templates/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
      notify: restart dnsmasq

    - name: Ensure dnsmasq is enabled and started
      systemd:
        name: dnsmasq
        state: started
        enabled: yes

  handlers:
    - name: restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted