apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.projectName }}-{{ .Values.global.entityId}}-litellm
  namespace: {{ .Release.Namespace }}
  labels:
    app: litellm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: litellm