apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.projectName }}-{{ .Values.global.entityId}}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.openwebui.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.litellm.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.litellm.openrouter.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}